name: CI Demo Tests

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  testcafe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Wait for GitHub Pages Deployment
        run: sleep 40  # 40-second delay to allow deployment to complete
      - run: npm run test:testcafe
      - name: Upload TestCafe Report
        uses: actions/upload-artifact@v2
        with:
          name: testcafe-report
          path: reports/testcafe-report.html

  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Wait for GitHub Pages Deployment
        run: sleep 40  # Delay to allow deployment to complete
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Create Reports Directory
        run: mkdir -p reports/playwright-report
      - name: Run Playwright tests
        run: npm run test:playwright
        continue-on-error: true  # Ensure the workflow continues even if tests fail
      - name: List All Files in Root Directory
        run: ls -al  # List all files and folders in the root of the project
      - name: List Test Results Directory
        run: ls -al test-results
      - name: List Playwright Report Directory
        run: ls -al reports/playwright-report  # List the contents of the report directory
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: reports/playwright-report

