name: CI Demo Tests

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  testcafe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Wait for GitHub Pages Deployment
        run: sleep 40  # 40-second delay to allow deployment to complete
      - run: npm run test:testcafe
      - name: Upload TestCafe Report
        uses: actions/upload-artifact@v2
        with:
          name: testcafe-report
          path: reports/testcafe-report.html

  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Wait for GitHub Pages Deployment
        run: sleep 40  # 40-second delay to allow deployment to complete
      - name: Install Playwright Browsers
        run: npx playwright install
      - run: npm run test:playwright
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: reports/playwright-report
