name: CI Demo Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Build Project
        run: npm run build  # Ensure the project is built before tests run

  testcafe:
    runs-on: ubuntu-latest
    needs: build  # This job will wait for the "build" job to finish
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test:testcafe

  playwright:
    runs-on: ubuntu-latest
    needs: build  # This job will also wait for the "build" job to finish
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install
      - run: npm run test:playwright
